--DROP TABLE IF EXISTS PRICES;
--DROP TABLE IF EXISTS BRAND;
--DROP TABLE IF EXISTS PRICE_LIST;
--DROP TABLE IF EXISTS CURRENCY;
--DROP TABLE IF EXISTS PRODUCT;


CREATE TABLE IF NOT EXISTS BRAND (
  BRAND_ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR2 NOT NULL,
  ADDRESS VARCHAR2 NOT NULL,
  PRIMARY KEY (BRAND_ID));


CREATE TABLE IF NOT EXISTS CURRENCY (
  CURRENCY_ID INT NOT NULL AUTO_INCREMENT,
  ACRONYM VARCHAR2 NOT NULL,
  DESCRIPTION VARCHAR2 NOT NULL,
  PRIMARY KEY (CURRENCY_ID));


CREATE TABLE IF NOT EXISTS PRODUCT (
  PRODUCT_ID INT NOT NULL ,
  NAME VARCHAR2 NOT NULL,
  PRIMARY KEY (PRODUCT_ID));


CREATE TABLE IF NOT EXISTS PRICE_LIST (
  PRICE_LIST_ID INT NOT NULL AUTO_INCREMENT,
  PRICE DOUBLE NOT NULL,
  PRIMARY KEY (PRICE_LIST_ID));


  CREATE TABLE IF NOT EXISTS PRICES (
    PRICES_ID INT NOT NULL AUTO_INCREMENT,
    START_DATE TIMESTAMP  NOT NULL,
    END_DATE TIMESTAMP  NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    CURRENCY_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRICE_LIST_ID INT NOT NULL,
    BRAND_ID INT NOT NULL,
    PRIMARY KEY (PRICES_ID),
    CONSTRAINT fk_PRICES_CURRENCY
      FOREIGN KEY (CURRENCY_ID)
      REFERENCES CURRENCY (CURRENCY_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT fk_PRICES_PRODUCT1
      FOREIGN KEY (PRODUCT_ID)
      REFERENCES PRODUCT (PRODUCT_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT fk_PRICES_PRICE_LIST1
      FOREIGN KEY (PRICE_LIST_ID)
      REFERENCES PRICE_LIST (PRICE_LIST_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT fk_PRICES_BRAND1
      FOREIGN KEY (BRAND_ID)
      REFERENCES BRAND (BRAND_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);